#!/bin/bash

URL=$1

DOWNLOAD_DIR="$HOME/Music/youtube"

mkdir -p "$DOWNLOAD_DIR"

if [ -z "$URL" ]; then
    echo ""
    echo "Usage:"
    echo "ytmp3 <youtube-url>"
    echo ""
    exit 1
fi

echo ""
echo "Downloading audio..."
echo ""

yt-dlp \
    --extract-audio \
    --audio-format mp3 \
    --audio-quality 0 \
    --embed-thumbnail \
    --add-metadata \
    --restrict-filenames \
    -o "$DOWNLOAD_DIR/%(title)s.%(ext)s" \
    "$URL"

echo ""
echo "Finished."
echo "Saved in:"
echo "$DOWNLOAD_DIR"
echo ""
